# **REFERÊNCIAS BIBLIOGRÁFICAS E ELETRÓNICAS**{-}

Agência para o Desenvolvimento e Coesão. (n.d.). Monitorização - Enquadramento. Obtido em 23 de agosto de 2022, de https://www.adcoesao.pt/fundos/portugal-2020/monitorizacao/enquadramento/  

Allers, M. A., & de Greef, J. A. (2017). Intermunicipal cooperation, public spending and service levels. Local Government Studies, 44(1), 127–150. https://doi.org/10.1080/03003930.2017.1380630  

Câmara Municipal de Santa Maria da Feira (2022). Relatório Final de Candidatura PIICIE do Município de Santa Maria da Feira.  

Carvalho, M., & Joana, L. (2020). Uma análise comparada: sistemas inspetivos de alguns países. Revista Lusófona de Educação, 50(50), 27–41. https://doi.org/10.24140/issn.1645-7250.rle50.02  

CCDR-Centro (2022). Programa Regional do Centro 2021-2027: Proposta. Obtido em 15 de setembro de 2022, de https://www.consultalex.gov.pt/ConsultaPublica_Detail.aspx?Consulta_Id=253  

CCDR-Norte. (2022). Programa Regional do Norte 2021-2027: Proposta. Obtido em 15 de setembro de 2022, de https://www.ccdr-n.pt/storage/app/media/uploaded-files/po20norte202030versc3a3oconsultapublica.pdf  

Decreto-Lei n.o 21/2019, de 30 de janeiro, do Ministério da Administração Interna. Diário da República n.o 21/2019, Série I (2019).  

Decreto-Lei n.º 54/2018, de 6 de julho, da Presidência do Conselho de Ministros. Diário da República n.º 129/2018, Série I (2018).  

Decreto-Lei n.o 7/2003, de 15 de janeiro, do Ministério das Cidades, Ordenamento do Território e Ambiente. Diário da República n.o 12/2003, Série I-A (2003).  

Decreto-Lei n.o 72/2015, de 11 de maio, da Presidência do Conselho de Ministros. Diário da República n.o 90/2015, Série I (2015).  

DGEEC, DGEstE, & IGeFE. (2021). Carta Educativa, Guião para Elaboração. Obtido em 30 de maio de 2022, de https://www.igefe.mec.pt/Files/DownloadDocument/17?csrt=5775597188220950806  

DGEEC. (2022a). Educação Inclusiva 2020/2021. Apoio à Aprendizagem e à Inclusão, escolas da rede pública do Ministério da Educação. Obtido em 23 de agosto de 2022, de https://www.dgeec.mec.pt/np4/%7B$clientServletPath%7D/?newsId=1363&fileName=EI2021_BreveSinteseResultados.pdf  

DGEEC. (2022a). Resultados Escolares: Sucesso e Equidade. Obtido em 13 de julho de 2022, de https://www.dgeec.mec.pt/np4/%7B$clientServletPath%7D/?newsId=1359&fileName=DGEEC_Relat_rio_Sucesso_Equidade_2022.pdf  

DGEEC. (2022b). Plano 21|23 Escola+. Segundo relatório de monitorização. Obtido em 23 de agosto de 2022, de https://www.dgeec.mec.pt/np4/%7B$clientServletPath%7D/?newsId=1369&fileName=DGEEC_SegundoRelatorio_de_Monitorizacao_.pdf  

DGEEC. (2022b). Taxa de retenção e desistência (%), por sexo, nível de ensino, ciclo de estudos e ano de escolaridade - Continente, NUTS II, III e Municípios – 2003/04 a 2020/21. Obtido em 3 de agosto de 2022, de https://www.dgeec.mec.pt/np4/248/  

Education Scotland. (2015). How good is our school? (4th edition). Obtido em 2 de setembro de 2022, de https://education.gov.scot/improvement/documents/frameworks_selfevaluation/frwk2_nihedithgios/frwk2_hgios4.pdf  

Ehren, M., & Shackleton, N. (2016). Risk-based school inspections: impact of targeted inspection approaches on Dutch secondary schools. Educational Assessment, Evaluation and Accountability, 28, 299–321. https://doi.org/10.1007/s11092-016-9242-0   

Garrone, P., Grilli, L., & Rousseau, X. (2012). Local Government Studies Management Discretion and Political Interference in Municipal Enterprises. Evidence from Italian Utilities. Local Government Studies, 39(4), 514-540. https://doi.org/10.1080/03003930.2012.726198  

Gartner Glossary (n.d.). Information delivery. Obtido em 30 de setembro de 2022, de https://www.gartner.com/en/information-technology/glossary/information-delivery 

Gaspar de Matos, M., Branquinho, C., Noronha, C., Moraes, B., Santos, O., Carvalho, M., Simões, C., Marques, A., Tomé, G., Guedes, F. B., Cerqueira, A., Francisco, R., & Gaspar, T. (2022). Observatório de Saúde Psicológica e Bem-Estar: Monitorização e Ação. Obtido em 23 de agosto de 2022, de https://www.dgeec.mec.pt/np4/%7B$clientServletPath%7D/?newsId=1357&fileName=SaudePsi_final.pdf  

Gendźwiłł, A., & Lackowska, M. (2018). A Borrowed Mandate? Democratic Legitimacy of Inter-municipal Entities: A Comparative Analysis. In F. Teles & P. Swianiewicz (Eds.), Inter-Municipal Cooperation in Europe (pp. 57–77). Palgrave Macmillan. https://doi.org/10.1007/978-3-319-62819-6  

IESE, ISCTE, & PPLL Consult. (2021). Avaliação do Contributo do PT2020 para a Promoção do Sucesso Educativo, Redução do Abandono Escolar Precoce e Empregabilidade dos Jovens. https://doi.org/10.38116/bapi25  

INE. (2021). População residente (N.o) por Local de residência, Sexo e Níveis de ensino; Decenal - INE, Recenseamento da população e habitação - Censos 2021. Obtido em 23 de agosto de 2022, de https://www.ine.pt/xportal/xmain?xpid=INE&xpgid=ine_indicadores&indOcorrCod=0011168&xlang=pt  

Inspeção-Geral da Educação e Ciência (IGEC). (2016). Quadro de referência para a avaliação externa das escolas. Obtido em 23 de agosto de 2022, de https://www.igec.mec.pt/upload/AEE_2016-2017/AEE_16_17_(1)_Quadro_de_Referencia.pdf  

Inspeção-Geral da Educação e Ciência (IGEC). (2018a). Terceiro Ciclo da Avaliação Externa das Escolas - Âmbito, princípios e objetivos. Obtido em 23 de agosto de 2022, de https://www.igec.mec.pt/upload/AEE3_2018/AEE_3_Amb_princ_objetivos.pdf  

Inspeção-Geral da Educação e Ciência (IGEC). (2018b). Terceiro Ciclo da Avaliação Externa das Escolas - Quadro de referência. Obtido em 23 de agosto de 2022, de https://www.igec.mec.pt/upload/AEE3_2018/AEE_3_Quadro_Ref.pdf  

Ioannidou, A. (2010). Educational monitoring and reporting as governance instruments for evidence-based education policy. International Perspectives on Education and Society, 12, 155–172. https://doi.org/10.1108/S1479-3679(2010)0000012011/FULL/XML  

Mairate, A. (2007). The ‘added value’ of European Union Cohesion policy. Regional Studies, 40(2), 167–177. https://doi.org/10.1080/00343400600600496  

Marques, J. L., Neves, R., Grifo, A., Duarte, J., Malta, J., Sousa, M. P., & Santos, S. (n.d.). Plano Estratégico Educativo Municipal de Santa Maria da Feira 2022-2030.  

Marques, J. L., Wolf, J., Borges, M., & Batista, P. (2020). Sistemas de apoio à decisão em planeamento: desafios metodológicos e conceptuais. TPU: Território, Planeamento e Urbanismo: Teoria e Prática, 2, 52–79. https://doi.org/10.34624/TPU.V0I2.23720  

Microsoft Power, B. I. Versão: 2.109.844.0 64-bit (setembro de 2022)
Ministério da Educação, & Inspeção-Geral da Educação (IGE). (2010). Quadro de referência para a avaliação de escolas e agrupamentos de escolas. Obtido em 23 de agosto de 2022, de https://www.igec.mec.pt/upload/AEE_2011/AEE_10_11_Quadro_Referencia.pdf  

Ministério da Educação. (2011). Propostas para um novo ciclo de avaliação externa de escolas, Relatório Final, Grupo de Trabalho para a Avaliação Externa das Escolas 2011. Obtido em 23 de agosto de 2022, https://www.igec.mec.pt/upload/AEE2_2011/AEE2_GT_2011_RELATORIO_FINAL.pdf  

Nóvoa, A. (2013). The Blindness of Europe: New Fabrications in the European Educational Space. SISYPHUS Journal of Education, 1(1), 104–123. http://ec.europa.eu/europe2020/services/faqs/index_en.htm  

Oliveira, P., Clímaco, M., Carravilla, M., Sarrico, C., Azevedo, M., & Oliveira, J. (2006). Relatório final da actividade do Grupo de Trabalho para Avaliação das Escolas Dezembro 2006. Obtido em 25 de agosto de 2022, de https://www.igec.mec.pt/upload/Relatorios/AEE_06_RELATORIO_GT.pdf  

POCH. (2021). Novo indicador de equidade na educação. Obtido em 13 de julho de 2022, de https://www.poch.portugal2020.pt/pt-pt/Noticias/Paginas/noticia.aspx?nid=750  

Portugal 2030. (2022). Programa Demografia, Qualificações e Inclusão - Proposta de programa. Obtido em 26 de agosto de 2022, de https://portugal2030.pt/wp-content/uploads/2022/07/PDQI_Versa%CC%83o-Submetida_Consulta-Pu%CC%81blica.pdf  

Presidência do Conselho de Ministros. (2018). “Decreto-Lei 54/2018”. Diário da República 1ª série, 129 (julho): 2918 – 2928. https://data.dre.pt/eli/dec-lei/54/2018/07/06/p/dre/pt/html  

R Core Team (2022). R: A language and environment   for statistical computing. R Foundation for  Statistical Computing. Obtido de https://www.R-project.org/  

Santos, S., Duarte, J. & Marques, J. L. (2019). Quadro de referência aplicado aos instrumentos de gestão da rede e da política educativa à escala local. Revista de Desarrollo Sustentable, Negocios, Emprendimiento y Educación, 1(1), 1–19.  

The Educational Institute of Scotland (EIS). (2019). Education Scotland Inspections. Obtido de 23 de agosto de 2022, de  [https://education.gov.scot/](https://education.gov.scot/education-scotland/what-we-do/inspection-and-review/standards-and-evaluation-framework/08-what-do-we-focus-on-during-inspection-and-review/#:~:text=We%20take%20into%20account%20the,the%20capacity%20for%20continuous%20improvement)  

Verdasca, J. (2020). Contributos para o desenvolvimento de um sistema de auto e multirregulação educativa. Revista Portuguesa de Investigação Educacional, n.o Especial, 111–143. https://doi.org/10.34632/investigacaoeducacional.2020.8503  

Wickham, H., & Grolemund, G. (2016). R for data science: import, tidy, transform, visualize, and model data. O'Reilly Media, Inc.  

XXI Governo – República Portuguesa (2019). Modelo de Avaliação Externa das Escolas – novo ciclo / Avaliação externa alargada às escolas profissionais privadas e às escolas com contrato de associação/patrocínio. Nota à Comunicação Social. Obtido em 23 de agosto de 2022, de https://www.portugal.gov.pt/download-ficheiros/ficheiro.aspx?v=%3D%3DBAAAAB%2BLCAAAAAAABAAzN7Q0AQCs6SFGBAAAAA%3D%3D
